# Generated by Django 4.0.6 on 2022-07-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_quality', models.PositiveIntegerField(max_length=1000)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_curs_by_rub', models.FloatField(max_length=10)),
            ],
        ),
    ]
